---
# .about.yml project metadata
#
# Short name that acts as the project identifier (required)
name: cloud.gov

# Full proper name of the project (required)
full_name: cloud.gov Platform-As-A-Service

# The type of content in the repo
# values: app, docs, policy
type: app

# Describes whether a project team, working group/guild, etc. owns the repo (required)
# values: guild, working-group, project
owner_type: project

# Name of the main project repo if this is a sub-repo; name of the working group/guild repo if this is a working group/guild subproject
# parent:

# Maturity stage of the project (required)
# values: discovery, alpha, beta, live
stage: beta

# Whether or not the project is actively maintained (required)
# values: active, deprecated
status: active

# Description of the project
description: cloud.gov takes care of infrastructure concerns so teams can focus all of their efforts on their app rather than fighting the environment

# Should be 'true' if the project has a continuous build (required)
# values: true, false
testable: true

# Team members contributing to the project (required)
# Items:
# - github: GitHub user name
#   id: Internal team identifier/user name
#   role: Team member's role; leads should be designated as 'lead'
team:
- github: mogul
  id: mogul
  role: Product Lead
- github: dlapiduz
  id: diego
  role: Product Owner
- github: ozzyjohnson
  id: ozzy
  role: Ops Engineer
- github: ramirezg
  id: gabriel.ramirez
  role: Ops Engineer
- github: jcscottiii
  id: jamescscott
  role: Ops Engineer

# Partners for whom the project is developed
partners:
- 18F
- GSA

# Brief descriptions of significant project developments
# milestones:
# - 

# Technologies used to build the project
stack:
- Cloud Foundry
- BOSH
- Amazon Web Services
- Docker
- AngularJS
- Bootstrap
- Grafana

# Brief description of the project's outcomes
impact: The cloud.gov PaaS has the potential to reduce costs and complexity of IT projects across the federal government by an order of magnitude.

# Services used to supply project status information
# Items:
# - name: Name of the service
#   category: Type of the service
#   url: URL for detailed information
#   badge: URL for the status badge
services:
- name: Status Page
  category: statuspage
  url: https://cloudgov.statuspage.io
- name: Travis CI
  category: continuousintegration
  url: https://travis-ci.org/18F/cf-landing
  badge: https://travis-ci.org/18F/cf-landing.svg?branch=master

# Licenses that apply to the project and/or its components (required)
# Items by property name pattern:
#   .*:
#     name: Name of the license from the Software Package Data Exchange (SPDX): https://spdx.org/licenses/
#     url: URL for the text of the license
licenses:
  .*:
    name: CC0
    url: https://github.com/18F/cf-landing/blob/master/LICENSE.md

# Blogs or websites associated with project development
blog:
- https://cloud.18f.gov

# Links to project artifacts
# Items:
# - url: URL for the link
#   text: Anchor text for the link
links:
- url: https://18f.storiesonboard.com/m/gov-dev
  text: Roadmap/ChangeLog story map (in StoriesOnBoard)
- url: https://trello.com/b/ChGzyepo/gov-dev  
  text: Sprint Status (in Trello)
- url: https://www.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks%40group.calendar.google.com&ctz=America/Los_Angeles
  text: Project Calendar (standups, reviews, and planning meetings)

# Email addresses of points-of-contact
contact:
- mailto:bret.mogilefsky@gsa.gov
