language: ruby
rvm:
- 2.1

install: gem install jekyll html-proofer about_yml
script: about_yml_validate ./.about.yml && jekyll build && htmlproof ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.cloud.gov
  username: bret.mogilefsky@gsa.gov
  password:
    secure: SJl5go/dkM0/aeWFM831qxw4WVx8eWCCR/g4X9f/OS1xa99o+hSFjz0xp35Q7vMf95NRVP4YYwQvrHMGiJX+PN3Y9GNntkQZ2KUTAsOwC09D/qS2RG9OvGDLdo/Uh73l/zJsV3/3M8QfUuyijULk6mhl+2STSoWJhljfdtzQUBxohI6YH7IUve+4E10LZD0TSgXcgSXrl/m/iXJz/NytoeGYsN7BWAZI94G4Rvcmn1g3X/+LuZkjx1VWP5u01fjQFVmbBYs0WKJX+g+z6jajITiKcjpKcOqJzyMT9unzyriBafvznNX92/AiDeLw8C10YUUx6B3Eqm+8/sag8R6P5g31QtdYR8Mw1nzka7peu86QfN5MHWqLOP/WDbPKQsAfzp5NnDH2hGgSbG1wsmdhmFuFKkuiR0H+fUhIXbLtgS6hse9OEBXFK7H4cKaRpDKAeNC0+IBVCsakJ+GcfsQn+9UJGS44ihZQWoI2gb/jncq1KN/RMjydFGTSN3TnUv/gk1XFVTFNo2rCykpw4dAQuJ+xTrkHE5EVTlczTJdYt13vh3ONWxA8tT7MnuOFhTYE2O2GT5ZRfBt2ZEHnA02xfoOuPId2SvAXY6SPRiBTlOUYYkf6j/Di2SygJsQhhZ8VnANFRCFqzK5TbcXaI+o4Nmu154bUVMDO9x9tvZyRNgo=
  organization: cf
  space: landing
  on:
    repo: 18F/cf-landing
    branch: master

