platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3-alpine
inputs:
- name: cg-landing-source
outputs:
- name: cg-landing-compiled
run:
  dir: cg-landing-source
  path: ci/build.sh
